src/main/java/ec/com/redepronik/negosys/invfac/entity/Anexos.java
package ec.com.redepronik.negosys.invfac.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "anexos")
public class Anexos implements Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String anio;
	private String mes;
	private String anexo;
	private Timestamp fecha;
	private BigDecimal tventa0;
	private BigDecimal tventa12;
	private BigDecimal tcompra0;
	private BigDecimal tcompra12;

	public Anexos() {
	}

	public Anexos(Integer id, String anio, String mes, String anexo, Timestamp fecha, BigDecimal tventa0,
			BigDecimal tventa12, BigDecimal tcompra0, BigDecimal tcompra12) {
		this.id = id;
		this.anio = anio;
		this.mes = mes;
		this.anexo = anexo;
		this.fecha = fecha;
		this.tventa0 = tventa0;
		this.tventa12 = tventa12;
		this.tcompra0 = tcompra0;
		this.tcompra12 = tcompra12;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Anexos other = (Anexos) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Id
	@SequenceGenerator(allocationSize = 1, name = "ANEXOS_ID_GENERATOR", sequenceName = "ANEXOS_ID_SEQ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ANEXOS_ID_GENERATOR")
	@Column(unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	@Column(length = 4, nullable = false)
	public String getAnio() {
		return anio;
	}

	@Column(length = 2, nullable = false)
	public String getMes() {
		return mes;
	}

	@Column(nullable = false)
	public String getAnexo() {
		return anexo;
	}

	@Column(nullable = false)
	public Timestamp getFecha() {
		return fecha;
	}

	@Column(nullable = false, precision = 8, scale = 2)
	public BigDecimal getTventa0() {
		return tventa0;
	}

	@Column(nullable = false, precision = 8, scale = 2)
	public BigDecimal getTventa12() {
		return tventa12;
	}

	@Column(nullable = false, precision = 8, scale = 2)
	public BigDecimal getTcompra0() {
		return tcompra0;
	}

	@Column(nullable = false, precision = 8, scale = 2)
	public BigDecimal getTcompra12() {
		return tcompra12;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setAnio(String anio) {
		this.anio = anio;
	}

	public void setMes(String mes) {
		this.mes = mes;
	}

	public void setAnexo(String anexo) {
		this.anexo = anexo;
	}

	public void setFecha(Timestamp fecha) {
		this.fecha = fecha;
	}

	public void setTventa0(BigDecimal tventa0) {
		this.tventa0 = tventa0;
	}

	public void setTventa12(BigDecimal tventa12) {
		this.tventa12 = tventa12;
	}

	public void setTcompra0(BigDecimal tcompra0) {
		this.tcompra0 = tcompra0;
	}

	public void setTcompra12(BigDecimal tcompra12) {
		this.tcompra12 = tcompra12;
	}

}

src/main/java/ec/com/redepronik/negosys/invfac/controller/AnexosBean.java
package ec.com.redepronik.negosys.invfac.controller;

import static ec.com.redepronik.negosys.utils.UtilsAplicacion.presentaMensaje;

import java.io.IOException;
import java.util.List;

import javax.faces.application.FacesMessage;

import org.primefaces.event.FileUploadEvent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import ec.com.redepronik.negosys.invfac.entity.Anexos;
import ec.com.redepronik.negosys.invfac.entityAux.Anio;
import ec.com.redepronik.negosys.invfac.entityAux.Mes;
import ec.com.redepronik.negosys.invfac.service.AnexosService;
import ec.com.redepronik.negosys.utils.anexo.Anexo;
import ec.com.redepronik.negosys.utils.service.ReporteService;

@Controller
@Scope("session")
public class AnexosBean {

	@Autowired
	private AnexosService anexosService;

	@Autowired
	private ReporteService reporteService;

	private List<Anexos> listaAnexos;
	private Anexos anexos;
	private Mes mesAnexo;
	private Anio anioAnexo;

	public Mes[] getListaMes() {
		return Mes.values();
	}

	public Anio[] getListaAnio() {
		return Anio.values();
	}

	public void obtener() {
		listaAnexos = anexosService.obtenerPorMes(anioAnexo, mesAnexo);
	}

	public void insertar(FileUploadEvent event) {
		try {
			anexosService.insertar(event.getFile().getInputstream());
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	public void eliminar() {
		anexosService.eliminar(anexos);
		obtener();
	}

	public void generar() {
		Anexo anexo = anexosService.generarAnexoFinal(anioAnexo, mesAnexo);
		if (anexo != null)
			reporteService.generarReporteXML(Anexo.class, "AT-" + mesAnexo.getId() + anioAnexo.getId(), anexo);
		else
			presentaMensaje(FacesMessage.SEVERITY_ERROR, "EL MES NO ESTA ACTIVO");
	}

	public List<Anexos> getListaAnexos() {
		return listaAnexos;
	}

	public void setListaAnexos(List<Anexos> listaAnexos) {
		this.listaAnexos = listaAnexos;
	}

	public Anexos getAnexos() {
		return anexos;
	}

	public void setAnexos(Anexos anexos) {
		this.anexos = anexos;
	}

	public Mes getMesAnexo() {
		return mesAnexo;
	}

	public void setMesAnexo(Mes mesAnexo) {
		this.mesAnexo = mesAnexo;
	}

	public Anio getAnioAnexo() {
		return anioAnexo;
	}

	public void setAnioAnexo(Anio anioAnexo) {
		this.anioAnexo = anioAnexo;
	}

}

src/main/java/ec/com/redepronik/negosys/invfac/controller/ListadoAnuladoBean.java
package ec.com.redepronik.negosys.invfac.controller;

import static ec.com.redepronik.negosys.utils.UtilsAplicacion.presentaMensaje;

import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import ec.com.redepronik.negosys.invfac.entity.Anulado;
import ec.com.redepronik.negosys.invfac.entity.TipoComprobante;
import ec.com.redepronik.negosys.invfac.service.AnuladoService;

@Controller
@Scope("session")
public class ListadoAnuladoBean {

	@Autowired
	private AnuladoService anuladoService;

	private List<Anulado> listaAnulados;
	private Anulado anulado;
	private TipoComprobante criterioBusquedaTipoComprobante;
	private String criterioBusquedaNumeroComprobante;
	private Date criterioBusquedaFecha;

	public ListadoAnuladoBean() {
	}

	public TipoComprobante[] getListaComprobantes() {
		return TipoComprobante.values();
	}

	public List<Anulado> getListaAnulados() {
		return listaAnulados;
	}

	public void setListaAnulados(List<Anulado> listaAnulados) {
		this.listaAnulados = listaAnulados;
	}

	public Anulado getAnulado() {
		return anulado;
	}

	public void setAnulado(Anulado anulado) {
		this.anulado = anulado;
	}

	public TipoComprobante getCriterioBusquedaTipoComprobante() {
		return criterioBusquedaTipoComprobante;
	}

	public void setCriterioBusquedaTipoComprobante(TipoComprobante criterioBusquedaTipoComprobante) {
		this.criterioBusquedaTipoComprobante = criterioBusquedaTipoComprobante;
	}

	public String getCriterioBusquedaNumeroComprobante() {
		return criterioBusquedaNumeroComprobante;
	}

	public void setCriterioBusquedaNumeroComprobante(String criterioBusquedaNumeroComprobante) {
		this.criterioBusquedaNumeroComprobante = criterioBusquedaNumeroComprobante;
	}

	public Date getCriterioBusquedaFecha() {
		return criterioBusquedaFecha;
	}

	public void setCriterioBusquedaFecha(Date criterioBusquedaFecha) {
		this.criterioBusquedaFecha = criterioBusquedaFecha;
	}

	@PostConstruct
	public void init() {
		anulado = new Anulado();
	}

	public void obtener() {
		listaAnulados = anuladoService.obtener(criterioBusquedaTipoComprobante, criterioBusquedaNumeroComprobante,
				criterioBusquedaFecha);
	}

	public void insertar() {
		if (anulado.getTipoComprobante() == null)
			presentaMensaje(FacesMessage.SEVERITY_WARN, "ESCOJA UN TIPO DE COMPROBANTE", "cerrar", false);
		else if (anulado.getEstablecimiento().compareTo("") == 0)
			presentaMensaje(FacesMessage.SEVERITY_WARN, "INGRESE UN ESTABLECIMIENTO");
		else if (anulado.getPuntoEmision().compareTo("") == 0)
			presentaMensaje(FacesMessage.SEVERITY_WARN, "INGRESE UN PTO. EMISION");
		else if (anulado.getSecuenciaInicio().compareTo("") == 0)
			presentaMensaje(FacesMessage.SEVERITY_WARN, "INGRESE UNA SECUENCIA DE INICIO");
		else if (anulado.getSecuenciaFin().compareTo("") == 0)
			presentaMensaje(FacesMessage.SEVERITY_WARN, "INGRESE UNA SECUENCIA DE FIN");
		else if (anulado.getAutorizacion().compareTo("") == 0)
			presentaMensaje(FacesMessage.SEVERITY_WARN, "INGRESE EL NUMERO DE AUTORIZACION", "cerrar", false);
		else {
			if (anuladoService.insertar(anulado)) {
				presentaMensaje(FacesMessage.SEVERITY_INFO,
						"SE AGREGO CORRECTAMENTE EL COMPROBANTE " + anulado.getTipoComprobante().getNombre(), "cerrar",
						true);
				anulado = new Anulado();
			}
		}
	}

	public void pasarSecuencia() {
		anulado.setSecuenciaInicio(String.format("%09d", Integer.parseInt(anulado.getSecuenciaInicio())));
		anulado.setSecuenciaFin(String.format("%09d", Integer.parseInt(anulado.getSecuenciaInicio())));
	}

}

src/main/webapp/views/tributacion/anexos.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" template="/WEB-INF/template.xhtml">

	<ui:define name="title">Anexos</ui:define>

	<ui:define name="content">
		<p:panel id="panelPrincipal" header="Anexos">
			<h:form id="busquedaTabla">
				<p:focus for="busquedaTabla" />
				<p:outputLabel value="Año" styleClass="DispBlock" />
				<p:selectOneMenu id="anio" value="#{anexosBean.anioAnexo}"
					styleClass="DispBlock Wid90">
					<f:selectItems value="#{anexosBean.listaAnio}" var="anio"
						itemValue="#{anio}" itemLabel="#{anio.id}" />
				</p:selectOneMenu>
				<p:outputLabel value="Mes" styleClass="DispBlock" />
				<p:selectOneMenu id="mes" value="#{anexosBean.mesAnexo}"
					styleClass="DispBlock Wid90">
					<f:selectItems value="#{anexosBean.listaMes}" var="mes"
						itemValue="#{mes}" itemLabel="#{mes.nombre}" />
				</p:selectOneMenu>
				<div class="EmptyBox10"></div>
				<p:commandButton update="busquedaTabla, :formDataTable, :mensaje"
					icon="#{msg['i.buscar']}" value="#{msg['btn.buscar']}"
					actionListener="#{anexosBean.obtener}" />
				<p:commandButton ajax="false" icon="#{msg['i.generar']}"
					value="#{msg['btn.generarXML']}"
					actionListener="#{anexosBean.generar}" />
				<div class="EmptyBox10"></div>
			</h:form>
			<h:form id="formDataTable">
				<p:dataTable id="tablaAnulados" var="anexos" paginator="true"
					scrollable="true" reflow="true" rows="10"
					value="#{anexosBean.listaAnexos}"
					paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
					paginatorPosition="bottom"
					emptyMessage="#{msg['lbl.mensajeTabla']}">
					<f:facet name="header">
						<p:tooltip for="btnNuevo" value="#{msg['lbl.insertar']}" />
						<p:commandButton id="btnNuevo"
							oncomplete="PF('dialogoImportar').show()"
							icon="#{msg['i.nuevo']}" />
					</f:facet>
					<p:column headerText="#{msg['lbl.gestionar']}" styleClass="centrar">
						<p:commandButton id="btnEliminar" update=":formEliminar"
							oncomplete="mostarPanelEliminar('')" icon="#{msg['i.eliminar']}">
							<f:setPropertyActionListener value="#{anexos}"
								target="#{anexosBean.anexos}" />
						</p:commandButton>
					</p:column>
					<p:column headerText="Año">
						<p:outputLabel value="#{anexos.anio}" />
					</p:column>
					<p:column headerText="Mes">
						<p:outputLabel value="#{anexos.mes}" />
					</p:column>
					<p:column headerText="Fecha">
						<p:outputLabel value="#{anexos.fecha}">
							<f:convertDateTime pattern="dd/MM/yyyy"
								timeZone="America/Guayaquil" />
						</p:outputLabel>
					</p:column>
					<p:column headerText="T. Venta 0%">
						<p:outputLabel value="#{anexos.tventa0}" />
					</p:column>
					<p:column headerText="T. Venta 12%">
						<p:outputLabel value="#{anexos.tventa12}" />
					</p:column>
					<p:column headerText="T. Compra 0%">
						<p:outputLabel value="#{anexos.tcompra0}" />
					</p:column>
					<p:column headerText="T. Compra 12%">
						<p:outputLabel value="#{anexos.tcompra12}" />
					</p:column>
				</p:dataTable>
			</h:form>
		</p:panel>

		<p:dialog header="Importar Anexo" widgetVar="dialogoImportar"
			resizable="false" modal="false" showEffect="clip" hideEffect="fold"
			id="dialogoImportar">
			<h:form id="formInsertar">
				<h:outputText value="Importar" styleClass="negrita" />
				<p:fileUpload fileUploadListener="#{anexosBean.insertar}"
					mode="advanced" dragDropSupport="true" multiple="true"
					update=":mensaje, @this" fileLimit="1" allowTypes="/(\.|\/)(xml)$/" />
			</h:form>
		</p:dialog>

		<p:panel id="panelEliminar" header="#{msg['lbl.desactivar']}"
			styleClass="DispNone">
			<h:form id="formEliminar">
				<h:inputHidden value="#{anexosBean.anexos.id}" />
				<div class="EmptyBox30"></div>
				<p:outputLabel value="¿Desea #{msg['lbl.desactivar']} el Anexo?" />
				<div class="EmptyBox30"></div>
				<p:separator />
				<p:commandButton value="#{msg['btn.aceptar']}"
					update=":formDataTable,:mensaje" icon="#{msg['i.activar']}"
					oncomplete="mostarPanelEliminar('')"
					actionListener="#{anexosBean.eliminar}" styleClass="GreenButton" />
				<p:commandButton value="#{msg['btn.cancelar']}"
					onclick="mostarPanelEliminar('')" icon="#{msg['i.cancelar']}"
					styleClass="RedButton" />
			</h:form>
		</p:panel>
	</ui:define>
</ui:composition>

src/main/webapp/views/tributacion/listadoAnulados.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" template="/WEB-INF/template.xhtml">

	<ui:define name="title">Comp. Anulados</ui:define>

	<ui:define name="content">
		<p:panel id="panelPrincipal" header="Comp. Anulados">
			<h:form id="busquedaTabla">
				<p:focus for="busquedaTabla" />
				<p:outputLabel value="Comprobante" styleClass="DispBlock" />
				<p:selectOneMenu id="comboComprobante"
					value="#{listadoAnuladoBean.criterioBusquedaTipoComprobante}"
					styleClass="DispBlock Wid90">
					<f:selectItem itemLabel="Escoja un Comprobante" itemValue="" />
					<f:selectItems value="#{listadoAnuladoBean.listaComprobantes}"
						var="comprobante" itemValue="#{comprobante}"
						itemLabel="#{comprobante.id}-#{comprobante.nombre}" />
				</p:selectOneMenu>
				<p:outputLabel value="# Documento" styleClass="DispBlock" />
				<p:inputText id="txtAutorizacion"
					value="#{listadoAnuladoBean.criterioBusquedaNumeroComprobante}"
					styleClass="DispBlock Wid90" />
				<p:outputLabel value="Fecha" styleClass="DispBlock" />
				<p:calendar id="inline"
					value="#{listadoAnuladoBean.criterioBusquedaFecha}"
					styleClass="DispBlock Wid90 calendario" />
				<div class="EmptyBox10"></div>
				<p:commandButton update="busquedaTabla, :formDataTable, :mensaje"
					icon="#{msg['i.buscar']}" value="#{msg['btn.buscar']}"
					actionListener="#{listadoAnuladoBean.obtener}" />
				<div class="EmptyBox10"></div>
			</h:form>
			<h:form id="formDataTable">
				<p:dataTable id="tablaAnulados" var="anulado" paginator="true"
					scrollable="true" reflow="true" rows="10"
					value="#{listadoAnuladoBean.listaAnulados}"
					paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
					paginatorPosition="bottom"
					emptyMessage="#{msg['lbl.mensajeTabla']}">
					<f:facet name="header">
						<p:tooltip for="btnNuevo" value="#{msg['lbl.insertar']}" />
						<p:commandButton id="btnNuevo"
							oncomplete="mostarPanelInsertar('')" icon="#{msg['i.nuevo']}" />
					</f:facet>
					<p:column headerText="Tipo Comprobante">
						<p:outputLabel
							value="#{anulado.tipoComprobante.id}-#{anulado.tipoComprobante.nombre}" />
					</p:column>
					<p:column headerText="Establecimiento">
						<p:outputLabel value="#{anulado.establecimiento}" />
					</p:column>
					<p:column headerText="Pto. Emision">
						<p:outputLabel value="#{anulado.puntoEmision}" />
					</p:column>
					<p:column headerText="Secuencia Inicio">
						<p:outputLabel value="#{anulado.secuenciaInicio}" />
					</p:column>
					<p:column headerText="Secuencia Fin">
						<p:outputLabel value="#{anulado.secuenciaFin}" />
					</p:column>
					<p:column headerText="Autorizacion">
						<p:outputLabel value="#{anulado.autorizacion}" />
					</p:column>
					<p:column headerText="Fecha">
						<p:outputLabel value="#{anulado.fechaAnulado}">
							<f:convertDateTime pattern="dd/MM/yyyy"
								timeZone="America/Guayaquil" />
						</p:outputLabel>
					</p:column>
				</p:dataTable>
			</h:form>
		</p:panel>

		<p:panel id="panelInsertar" header="#{msg['lbl.insertar']}"
			styleClass="DispNone">
			<h:form id="formInsertarAnulado">
				<p:outputLabel value="Comprobante" styleClass="DispBlock" />
				<p:selectOneMenu id="comboComprobante"
					value="#{listadoAnuladoBean.anulado.tipoComprobante}"
					styleClass="DispBlock Wid90">
					<f:selectItem itemLabel="Escoja un Comprobante" itemValue="" />
					<f:selectItems value="#{listadoAnuladoBean.listaComprobantes}"
						var="comprobante" itemValue="#{comprobante}"
						itemLabel="#{comprobante.id}-#{comprobante.nombre}" />
				</p:selectOneMenu>
				<p:outputLabel value="Establecimiento" styleClass="DispBlock" />
				<p:inputText value="#{listadoAnuladoBean.anulado.establecimiento}"
					styleClass="DispBlock Wid90" />
				<p:outputLabel value="Pto. Emision" styleClass="DispBlock" />
				<p:inputText value="#{listadoAnuladoBean.anulado.puntoEmision}"
					styleClass="DispBlock Wid90" />
				<p:outputLabel value="Secuencia Inicio" styleClass="DispBlock" />
				<p:inputText id="txtSecInicio"
					value="#{listadoAnuladoBean.anulado.secuenciaInicio}"
					styleClass="DispBlock Wid90">
					<p:ajax event="blur"
						listener="#{listadoAnuladoBean.pasarSecuencia}"
						update="txtSecInicio, txtSecFin" />
				</p:inputText>
				<p:outputLabel value="Secuencia Fin" styleClass="DispBlock" />
				<p:inputText id="txtSecFin"
					value="#{listadoAnuladoBean.anulado.secuenciaFin}"
					styleClass="DispBlock Wid90" />
				<p:outputLabel value="Autorizacion" styleClass="DispBlock" />
				<p:inputText value="#{listadoAnuladoBean.anulado.autorizacion}"
					styleClass="DispBlock Wid90" />
				<p:separator />
				<p:commandButton value="#{msg['btn.guardar']}"
					update=":formInsertarAnulado, :mensaje"
					oncomplete="comprobarInsertar(xhr, status, args, '')"
					id="btnNuevoAceptar" icon="#{msg['i.guardar']}"
					actionListener="#{listadoAnuladoBean.insertar}"
					styleClass="GreenButton" />
				<p:commandButton value="#{msg['btn.cancelar']}"
					oncomplete="mostarPanelInsertar('')" id="btnNuevolimpiar"
					icon="#{msg['i.cancelar']}" process="@this" styleClass="RedButton" />
			</h:form>
		</p:panel>
	</ui:define>
</ui:composition>

src/main/webapp/views/tributacion/reportes.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" template="/WEB-INF/template.xhtml">

	<ui:define name="title">Reportes</ui:define>

	<ui:define name="content">
		<p:panel id="panel" header="Reportes">
			<h:form styleClass="TexAlCenter formReportes">
				<i class="fa fa-line-chart Fs130 blue DispBlock"></i>
				<p:outputLabel value="Fecha Inicio" styleClass="DispBlock" />
				<p:calendar value="#{tributacionReportes.fechaInicioRetenciones}"
					required="true" requiredMessage="Ingrese una Fecha de Inicio"
					styleClass="DispBlock Wid90 calendario" />
				<p:outputLabel value="Fecha Fin" styleClass="DispBlock" />
				<p:calendar value="#{tributacionReportes.fechaFinRetenciones}"
					required="true" requiredMessage="Ingrese una Fecha de Corte"
					styleClass="DispBlock Wid90 calendario" />
				<p:outputLabel value="Proveedores" styleClass="DispBlock" />
				<p:selectOneMenu value="#{tributacionReportes.proveedorId}"
					filter="true" filterMatchMode="contains"
					styleClass="DispBlock Wid90">
					<f:selectItem itemLabel="Todos" itemValue="0" />
					<f:selectItems value="#{tributacionReportes.listaProveedores}"
						var="persona" itemValue="#{persona.proveedor.id}"
						itemLabel="#{persona.proveedor.nombreComercial}" />
				</p:selectOneMenu>
				<div class="EmptyBox10"></div>
				<p:commandButton
					actionListener="#{tributacionReportes.reporteRetenciones}"
					value="Retenciones" ajax="false" styleClass="DispBlock Wid90" />
			</h:form>
			<h:form styleClass="TexAlCenter formReportes">
				<i class="fa fa-line-chart Fs130 blue DispBlock"></i>
				<p:outputLabel value="Año" styleClass="DispBlock" />
				<p:selectOneMenu id="anio" value="#{tributacionReportes.anioAnexo}"
					styleClass="DispBlock Wid90">
					<f:selectItems value="#{tributacionReportes.listaAnio}" var="anio"
						itemValue="#{anio}" itemLabel="#{anio.id}" />
				</p:selectOneMenu>
				<p:outputLabel value="Mes" styleClass="DispBlock" />
				<p:selectOneMenu id="mes" value="#{tributacionReportes.mesAnexo}"
					styleClass="DispBlock Wid90">
					<f:selectItems value="#{tributacionReportes.listaMes}" var="mes"
						itemValue="#{mes}" itemLabel="#{mes.nombre}" />
				</p:selectOneMenu>
				<div class="EmptyBox10"></div>
				<p:commandButton
					actionListener="#{tributacionReportes.reporteAnexo}" value="Anexo"
					ajax="false" styleClass="DispBlock Wid90" />
			</h:form>
		</p:panel>
	</ui:define>
</ui:composition>