src/main/java/ec/com/redepronik/negosys/invfac/controller/PedidoBean.java
package ec.com.redepronik.negosys.invfac.controller;

import static ec.com.redepronik.negosys.utils.UtilsAplicacion.presentaMensaje;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.event.ActionEvent;

import org.primefaces.event.SelectEvent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;

import ec.com.redepronik.negosys.invfac.entity.EstadoProductoVenta;
import ec.com.redepronik.negosys.invfac.entity.Local;
import ec.com.redepronik.negosys.invfac.entity.Pedido;
import ec.com.redepronik.negosys.invfac.entity.Producto;
import ec.com.redepronik.negosys.invfac.entityAux.CantidadFactura;
import ec.com.redepronik.negosys.invfac.entityAux.FacturaReporte;
import ec.com.redepronik.negosys.invfac.service.LocalService;
import ec.com.redepronik.negosys.invfac.service.PedidoService;
import ec.com.redepronik.negosys.invfac.service.ProductoService;
import ec.com.redepronik.negosys.rrhh.entity.Cliente;
import ec.com.redepronik.negosys.rrhh.entity.Persona;
import ec.com.redepronik.negosys.rrhh.service.ClienteService;
import ec.com.redepronik.negosys.rrhh.service.EmpleadoService;

@Controller
@Scope("session")
public class PedidoBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Autowired
	private PedidoService pedidoService;

	@Autowired
	private ProductoService productoService;

	@Autowired
	private ClienteService clienteService;

	@Autowired
	private LocalService localService;

	@Autowired
	private EmpleadoService empleadoService;

	private List<Local> listaLocales;
	private String nombreVendedor;

	private Pedido pedido;

	private List<FacturaReporte> listaFacturaReporte;
	private CantidadFactura cantidadFactura;

	private boolean bn = true;
	private boolean bnLocal;
	private Local local;

	// Cuadro de Busqueda de clientes
	private List<Persona> listaClienteBusqueda;
	private String criterioClienteBusqueda;

	private Producto producto;
	private String criterioBusquedaRapida;
	private List<Producto> listaBusquedaRapida;

	private long pedidoId;

	private String cliente;
	private Date fecha;

	public PedidoBean() {

	}

	public void busquedaRapida() {
		listaBusquedaRapida = productoService.obtenerPorLocal(criterioBusquedaRapida, null, local.getId());
	}

	public void cambiarCantidad(FacturaReporte facturaReporte) {
		int fila = listaFacturaReporte.indexOf(facturaReporte);
		cantidadFactura = pedidoService.calcularCantidad(facturaReporte, listaFacturaReporte, fecha);
		if (fila == listaFacturaReporte.size() - 1)
			listaFacturaReporte.add(new FacturaReporte());
	}

	public void cambiarDescDol(FacturaReporte facturaReporte) {
		cantidadFactura = pedidoService.calcularDescuentoDolares(facturaReporte, listaFacturaReporte, fecha);
	}

	public void cambiarDescPor(FacturaReporte facturaReporte) {
		cantidadFactura = pedidoService.calcularDescuentoPorcentaje(facturaReporte, listaFacturaReporte, fecha);
	}

	public void cambiarEstado(FacturaReporte facturaReporte) {
		cantidadFactura = pedidoService.cambiarEstado(facturaReporte, listaFacturaReporte, fecha);
	}

	public void cambiarImporte(FacturaReporte facturaReporte) {
		cantidadFactura = pedidoService.calcularImporte(facturaReporte, listaFacturaReporte, fecha);
	}

	public void cambiarPrecio(FacturaReporte facturaReporte) {
		cantidadFactura = pedidoService.calcularPrecio(facturaReporte, listaFacturaReporte, fecha);
	}

	public void cambiarTipoPrecio(FacturaReporte facturaReporte) {
		cantidadFactura = pedidoService.calcularTipoPrecio(facturaReporte, listaFacturaReporte, fecha);
	}

	public void cancelarTodo() {
		limpiarPedido();
		listaFacturaReporte = new ArrayList<FacturaReporte>();
		listaFacturaReporte.add(new FacturaReporte());
		cantidadFactura = new CantidadFactura();
		fecha = new Date();
	}

	public void cargarCliente() {
		pedido.setCliente(clienteService.cargarCliente(cliente));
	}

	public void cargarCliente(SelectEvent event) {
		Cliente c = clienteService.obtenerPorPersonaId(pedido.getCliente().getPersona().getId()).getCliente();
		pedido.setCliente(c);
	}

	public void cargarProducto(FacturaReporte facturaReporte) {
		if (pedidoService.cargarProductoLista(facturaReporte)) {
			listaFacturaReporte.get(listaFacturaReporte.size() - 1).setCantidad(1);
			cambiarCantidad(listaFacturaReporte.get(listaFacturaReporte.size() - 1));
		}
	}

	public boolean comprobarLocal() {
		if (pedido.getEstablecimiento() == null || pedido.getEstablecimiento().compareToIgnoreCase("") == 0) {
			presentaMensaje(FacesMessage.SEVERITY_ERROR, "ERROR: DEBE ESCOJER UN LOCAL");
			return false;
		}
		return true;
	}

	public boolean comprobarTodo() {
		if (pedido.getCliente().getPersona() == null) {
			presentaMensaje(FacesMessage.SEVERITY_ERROR, "ERROR: INGRESE UN CLIENTE");
			return true;
		} else if (pedido.getEstablecimiento() == null || pedido.getEstablecimiento().compareToIgnoreCase("") == 0) {
			presentaMensaje(FacesMessage.SEVERITY_ERROR, "ERROR: ESCOJA UN LOCAL");
			return true;
		} else if (pedido.getVendedor().getId() == 0) {
			presentaMensaje(FacesMessage.SEVERITY_ERROR, "ERROR: INGRESE UN VENDEDOR");
			return true;
		} else if (pedidoService.convertirListaFacturaReporteListaPedidoDetalle(listaFacturaReporte, pedido))
			return true;

		return false;
	}

	public CantidadFactura getCantidadFactura() {
		return pedidoService.redondearCantidadFactura(cantidadFactura);
	}

	public String getCliente() {
		return cliente;
	}

	public String getCriterioBusquedaRapida() {
		return criterioBusquedaRapida;
	}

	public String getCriterioClienteBusqueda() {
		return criterioClienteBusqueda;
	}

	public List<Producto> getListaBusquedaRapida() {
		return listaBusquedaRapida;
	}

	public List<Persona> getListaClienteBusqueda() {
		return listaClienteBusqueda;
	}

	public EstadoProductoVenta[] getListaEstadoProductoVenta() {
		return EstadoProductoVenta.values();
	}

	public List<FacturaReporte> getListaFacturaReporte() {
		return listaFacturaReporte;
	}

	public List<Local> getListaLocales() {

		return listaLocales;
	}

	public String getNombreVendedor() {
		return nombreVendedor;
	}

	public Pedido getPedido() {
		return pedido;
	}

	public Producto getProducto() {
		return producto;
	}

	public void imprimirPedido() {
		// if (pedidoReport.reporteFactura(pedidoId))
		cancelarTodo();
	}

	@PostConstruct
	public void init() {
		listaLocales = localService
				.obtenerPorCedulaAndCargo(SecurityContextHolder.getContext().getAuthentication().getName(), 4);
		cancelarTodo();
		bn = true;
	}

	public void insertar(ActionEvent actionEvent) {
		if (!comprobarTodo()) {
			bn = false;

			pedidoId = pedidoService.insertar(pedido).getId();
			if (pedidoId != 0) {
				bn = false;
				cancelarTodo();
			}
		}
	}

	public void insertarProductoRapido(SelectEvent event) {
		Producto producto = productoService.obtenerPorProductoId(((Producto) event.getObject()).getId());
		listaFacturaReporte.get(listaFacturaReporte.size() - 1).setProducto(producto);
		pedidoService.cargarProductoLista(listaFacturaReporte.get(listaFacturaReporte.size() - 1));
		listaFacturaReporte.add(new FacturaReporte());

		presentaMensaje(FacesMessage.SEVERITY_INFO, "AGREGÓ PRODUCTO " + producto.getNombre());
	}

	public boolean isBn() {
		return bn;
	}

	public boolean isBnLocal() {
		return bnLocal;
	}

	public void limpiarObjetosBusquedaCliente() {
		criterioClienteBusqueda = new String();
		listaClienteBusqueda = new ArrayList<Persona>();
	}

	private void limpiarPedido() {
		pedido = new Pedido();
		pedido.setCliente(new Cliente());
		setCliente("");

		String cedula = SecurityContextHolder.getContext().getAuthentication().getName();
		Persona persona = empleadoService.obtenerPorCedula(cedula);
		nombreVendedor = persona.getApellido().concat(" ").concat(persona.getNombre());
		pedido.setVendedor(empleadoService.obtenerEmpleadoCargoPorCedulaAndCargo(cedula, 5));

		if (listaLocales.size() == 1) {
			local = listaLocales.get(0);
			pedido.setEstablecimiento(local.getCodigoEstablecimiento());
			setBnLocal(false);
		} else {
			setBnLocal(true);
		}

	}

	public void nuevoPedido() {
		cancelarTodo();
		bn = true;
		pedidoId = 0L;
	}

	public List<String> obtenerClientePorBusqueda(String criterioClienteBusqueda) {
		List<String> lista = clienteService.obtenerListaClientesAutoComplete(criterioClienteBusqueda);
		if (lista.size() == 1) {
			cliente = (lista.get(0));
			cargarCliente();
		}
		return lista;
	}

	public void obtenerClientesPorBusqueda() {
		listaClienteBusqueda = clienteService.obtener(criterioClienteBusqueda, 0);
	}

	public List<String> obtenerProductosPorBusqueda(String criterioProductoBusqueda) {
		if (comprobarLocal())
			return productoService.obtenerListaStringPorLocal(criterioProductoBusqueda, local.getId());
		return new ArrayList<String>();
	}

	public void setBn(boolean bn) {
		this.bn = bn;
	}

	public void setBnLocal(boolean bnLocal) {
		this.bnLocal = bnLocal;
	}

	public void setCantidadFactura(CantidadFactura cantidadFactura) {
		this.cantidadFactura = cantidadFactura;
	}

	public void setCliente(String cliente) {
		this.cliente = cliente;
	}

	public void setCriterioBusquedaRapida(String criterioBusquedaRapida) {
		this.criterioBusquedaRapida = criterioBusquedaRapida;
	}

	public void setCriterioClienteBusqueda(String criterioClienteBusqueda) {
		this.criterioClienteBusqueda = criterioClienteBusqueda;
	}

	public void setListaBusquedaRapida(List<Producto> listaBusquedaRapida) {
		this.listaBusquedaRapida = listaBusquedaRapida;
	}

	public void setListaClienteBusqueda(List<Persona> listaClienteBusqueda) {
		this.listaClienteBusqueda = listaClienteBusqueda;
	}

src/main/java/ec/com/redepronik/negosys/rrhh/controller/ClienteBean.java
package ec.com.redepronik.negosys.rrhh.controller;

import static ec.com.redepronik.negosys.utils.Utils.expRegular;
import static ec.com.redepronik.negosys.utils.UtilsAplicacion.presentaMensaje;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.event.ActionEvent;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import ec.com.redepronik.negosys.rrhh.entity.Ciudad;
import ec.com.redepronik.negosys.rrhh.entity.Cliente;
import ec.com.redepronik.negosys.rrhh.entity.DetalleCliente;
import ec.com.redepronik.negosys.rrhh.entity.Persona;
import ec.com.redepronik.negosys.rrhh.entity.Provincia;
import ec.com.redepronik.negosys.rrhh.service.CiudadService;
import ec.com.redepronik.negosys.rrhh.service.ClienteService;
import ec.com.redepronik.negosys.rrhh.service.PersonaService;

@Controller
@Scope("session")
public class ClienteBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Autowired
	private PersonaService personaService;

	@Autowired
	private ClienteService clienteService;

	@Autowired
	private CiudadService ciudadService;

	private List<Persona> listaPersonasClientes;
	private Persona persona;
	private List<Ciudad> listaCiudadesBusqueda;
	private String criterioBusquedaCliente;
	private Integer criterioBusquedaCiudad;
	private List<Ciudad> listaCiudades;

	public ClienteBean() {

	}

	public void actualizar(ActionEvent actionEvent) {
		clienteService.actualizar(persona);
		listaPersonasClientes = new ArrayList<Persona>();
	}

	public void cargarCiudades() {
		listaCiudades = new ArrayList<>();
		listaCiudades = ciudadService.obtenerPorProvincia(persona.getCiudad().getProvincia());
	}

	public void cargarEditar() {
		cargarCiudades();
	}

	public void cargarInsertar() {
		limpiarObjetos();
	}

	public void comprobarPersona() {
		String cedula = persona.getCedula().trim();
		persona = personaService.obtenerPorCedula(cedula);
		if (persona != null && persona.getCliente() != null) {
			limpiarObjetos();
			presentaMensaje(FacesMessage.SEVERITY_ERROR, "EL CLIENTE YA EXISTE");
		} else if (persona != null) {
			persona.setCliente(new Cliente());
			persona.getCliente().setFolio(String.valueOf(clienteService.contar() + 1));
			persona.getCliente().setNombreComercial(persona.getApellido().concat(" ").concat(persona.getNombre()));
			cargarCiudades();
		} else {
			limpiarObjetos();
			persona.setCedula(cedula);
		}
	}

	public void eliminar(ActionEvent actionEvent) {
		clienteService.eliminar(persona);
	}

	public void eliminarAdicional(DetalleCliente detallecliente) {
		personaService.eliminarAdiconal(persona, detallecliente);
	}

	public Integer getCriterioBusquedaCiudad() {
		return criterioBusquedaCiudad;
	}

	public String getCriterioBusquedaCliente() {
		return criterioBusquedaCliente;
	}

	public List<Ciudad> getListaCiudades() {
		return listaCiudades;
	}

	public List<Ciudad> getListaCiudadesBusqueda() {
		return listaCiudadesBusqueda;
	}

	public List<Persona> getListaPersonasClientes() {
		return listaPersonasClientes;
	}

	public Provincia[] getListaProvincias() {
		return Provincia.values();
	}

	public Persona getPersona() {
		return persona;
	}

	@PostConstruct
	public void init() {
		listaCiudadesBusqueda = ciudadService.obtener(null);
		limpiarObjetos();
	}

	public void insertar(ActionEvent actionEvent) {
		clienteService.insertar(persona);
	}

	public void insertarFilaAdicional() {
		personaService.insertarFilaAdicional(persona);
	}

	public void limpiarObjetos() {
		persona = new Persona();
		persona.setEmail("");
		persona.setTelefono("");
		;

		persona.setCiudad(new Ciudad());

		persona.setCliente(new Cliente());

		persona.getCliente().setDetalleClientes(new ArrayList<DetalleCliente>());

		persona.getCliente().setFolio(String.valueOf(clienteService.contar() + 1));
	}

	public void obtenerClientes() {
		listaPersonasClientes = new ArrayList<Persona>();
		int codigoCliente = 0;
		if (expRegular(criterioBusquedaCliente, "(c|C){1,1}[0-9]+")) {
			codigoCliente = Integer.parseInt(criterioBusquedaCliente.substring(1));
			criterioBusquedaCliente = "";
		}
		listaPersonasClientes = clienteService.obtenerTodosPorBusqueda(criterioBusquedaCliente.toUpperCase(),
				criterioBusquedaCiudad, codigoCliente);
	}

	public void setCriterioBusquedaCiudad(Integer criterioBusquedaCiudad) {
		this.criterioBusquedaCiudad = criterioBusquedaCiudad;
	}

	public void setCriterioBusquedaCliente(String criterioBusquedaCliente) {
		this.criterioBusquedaCliente = criterioBusquedaCliente;
	}

	public void setListaCiudades(List<Ciudad> listaCiudades) {
		this.listaCiudades = listaCiudades;
	}

	public void setListaCiudadesBusqueda(List<Ciudad> listaCiudadesBusqueda) {
		this.listaCiudadesBusqueda = listaCiudadesBusqueda;
	}

	public void setListaPersonasClientes(List<Persona> listaPersonasClientes) {
		this.listaPersonasClientes = listaPersonasClientes;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}
}

src/main/webapp/views/m/nuevoPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" template="/WEB-INF/template.xhtml">

	<ui:define name="title">Nuevo Pedido</ui:define>

	<ui:define name="content">
		<p:panel id="panelPrincipal" header="Nuevo Pedido">
			<div id="datosPedido" class="divDatosIzq50">
				<h:form id="formCliente">
					<p:remoteCommand name="obtenerClienteRC"
						actionListener="#{nuevoPedidoBean.obtenerCliente}"
						update="txtCriterioCliente, :mensaje" />
					<p:outputLabel value="CLIENTE" styleClass="DispBlock" />
					<p:inputText id="txtCriterioCliente"
						placeholder="Ingrese el codigo del cliente"
						value="#{nuevoPedidoBean.cliente}" onblur="obtenerClienteRC()"
						onkeypress="if (event.keyCode == 13) { obtenerClienteRC(); return false; }"
						styleClass="DispBlock Wid90" />

					<p:outputLabel value="ESTABLEIMIENTO" styleClass="DispBlock" />
					<p:selectOneMenu id="comboLocal"
						value="#{nuevoPedidoBean.pedido.establecimiento}"
						styleClass="DispBlock Wid90">
						<f:selectItems value="#{nuevoPedidoBean.listaLocales}" var="local"
							itemValue="#{local.codigoEstablecimiento}"
							itemLabel="#{local.nombre}" />
						<p:ajax update="comboLocal" event="change" />
					</p:selectOneMenu>
				</h:form>
			</div>

			<div id="datosTotales" class="divDatosDer50">
				<h:form id="formTotales">
					<div id="datosIzq" class="divDatosIzq50">
						<h:outputText value="SUBTOTAL 12-14%:" styleClass="DispBlock" />
						<p:outputLabel id="subTotalIva" readonly="true"
							styleClass="DispBlock Wid90" />

						<h:outputText value="SUBTOTAL 0%:" styleClass="DispBlock" />
						<p:outputLabel id="subTotal0" readonly="true"
							styleClass="DispBlock Wid90" />

						<h:outputText value="SUBTOTAL SIN IMPUESTO:"
							styleClass="DispBlock" />
						<p:outputLabel id="subTotal" readonly="true"
							styleClass="DispBlock Wid90" />
					</div>
					<div id="datosDer" class="divDatosDer50">
						<h:outputText value="TOTAL DESCUENTO:" styleClass="DispBlock" />
						<p:outputLabel id="descuento" readonly="true"
							styleClass="DispBlock Wid90" />

						<h:outputText value="IVA 12-14% :" styleClass="DispBlock" />
						<p:outputLabel id="iva" readonly="true"
							styleClass="DispBlock Wid90" />

						<h:outputText value="VALOR TOTAL :" styleClass="DispBlock" />
						<p:outputLabel id="total" readonly="true"
							styleClass="DispBlock Wid90 red Fs20 FontBold" />
					</div>
				</h:form>
			</div>
			<div class="EmptyBox10"></div>
			<p:commandButton value="#{msg['btn.guardar']}"
				update=":formCliente, :formDataTable, :formTotales, :mensaje"
				actionListener="#{nuevoPedidoBean.insertar}"
				icon="#{msg['i.guardar']}" styleClass="GreenButton" />

			<p:commandButton value="#{msg['btn.nuevo']}"
				update=":formCliente, :formDataTable, :formTotales, :mensaje"
				icon="#{msg['i.nuevoDocumento']}"
				actionListener="#{nuevoPedidoBean.limpiar}"
				styleClass="OrangeButton" />
			<div class="EmptyBox10"></div>

			<h:form id="formDataTable">

				<p:dataTable id="tablaDetallePedido" var="facturaReporte"
					reflow="true" value="#{nuevoPedidoBean.listaFacturaReporte}"
					paginator="true" rows="10"
					emptyMessage="#{msg['lbl.mensajeTabla']}"
					paginatorPosition="bottom" scrollable="true">

					<f:facet name="header">
						<p:commandButton update=":formBusquedaProducto"
							onclick="mostarPanelInsertar('')" id="btnNuevo"
							icon="#{msg['i.nuevo']}" value="Insertar Producto" />
					</f:facet>

					<p:column headerText="Estado" styleClass="Wid7_5">
						<p:selectOneMenu id="estado" value="#{facturaReporte.estado}"
							styleClass="Wid90"
							onchange="cambiarEstado(this.id, #{facturaReporte.codigo});">
							<f:selectItems
								value="#{nuevoPedidoBean.listaEstadoProductoVenta}" var="estado"
								itemValue="#{estado}" itemLabel="#{estado.nombre}" />
						</p:selectOneMenu>
					</p:column>

					<p:column headerText="Imp." styleClass="Wid3">
						<h:outputLabel id="impuesto" value="#{facturaReporte.impuesto}" />
					</p:column>

					<p:column headerText="Producto" styleClass="Wid20">
						<p:outputLabel id="txtProducto"
							value="#{facturaReporte.codigo} || #{facturaReporte.descripcion}"
							styleClass="Wid90" />
					</p:column>

					<p:column headerText="Cantidad" styleClass="Wid7_5">
						<p:inputText id="cantidad" value="#{facturaReporte.cantidad}"
							styleClass="Wid90" onchange="calcularImporte(this.id);" />
					</p:column>

					<p:column headerText="Tipo Precio" styleClass="Wid7_5">
						<p:selectOneMenu id="tipoPrecio" 
							value="#{facturaReporte.precioId}" styleClass="Wid90"
							onchange="cambiarTipoPrecio(this.id, #{facturaReporte.codigo});">
							<f:selectItems 
								value="#{facturaReporte.producto.tipoPrecioProductos}"
								var="precio" itemValue="#{precio.id}"
								itemLabel="#{precio.nombre}" />
						</p:selectOneMenu>
					</p:column>

					<p:column headerText="P. Unit." styleClass="Wid7_5 TexAlRight">
						<p:outputLabel id="precioUnitario"
							value="#{facturaReporte.precioUnitVenta}" styleClass="Wid90" />
					</p:column>

					<p:column headerText="Importe" styleClass="Wid7_5 TexAlRight">
						<p:outputLabel id="importe" value="#{facturaReporte.importe}"
							styleClass="Wid90" />
					</p:column>

				</p:dataTable>
			</h:form>
		</p:panel>

		<p:panel id="panelInsertar" header="AÑADIR PRODUCTO"
			styleClass="DispNone">

			<h:form id="formBusquedaProducto">
				<p:outputLabel value="Producto" styleClass="DispBlock" />
				<p:inputText value="#{nuevoPedidoBean.criterioBusquedaRapida}"
					styleClass="Wid90 inputConButton" />
				<p:commandButton id="btnBusquedaRapida"
					update="tablaBusquedaProductos, :mensaje" icon="#{msg['i.buscar']}"
					actionListener="#{nuevoPedidoBean.busquedaRapida}"
					styleClass="botonBuscar" />

				<div class="EmptyBox10"></div>
				<p:commandButton value="Regresar"
					update=":formDataTable:tablaDetallePedido"
					actionListener="#{nuevoPedidoBean.guardarDetallePedido}"
					oncomplete="mostarPanelInsertar('');" id="btnAtras"
					icon="#{msg['i.atras']}" styleClass="OrangeButton" />
				<div class="EmptyBox10"></div>

				<p:dataTable id="tablaBusquedaProductos" var="producto"
					paginator="true" rows="10" scrollable="true"
					styleClass="ui-datatable-scrollable-body"
					value="#{nuevoPedidoBean.listaBusquedaRapida}" editable="true"
					emptyMessage="#{msg['lbl.mensajeTabla']}"
					paginatorPosition="bottom" selectionMode="single"
					selection="#{nuevoPedidoBean.producto}" rowKey="#{producto.id}">

					<p:ajax event="rowSelect"
						listener="#{nuevoPedidoBean.insertarProductoRapido}"
						update=":mensaje" />

					<p:column headerText="EAN" style="width:100px">
						#{producto.ean}
					</p:column>

					<p:column headerText="NOMBRE" style="width:300px">
						#{producto.nombre}
					</p:column>
				</p:dataTable>
			</h:form>
		</p:panel>
	</ui:define>
</ui:composition>